### ISSUE TITLE
When typing in a course number directly, that course is not the first search result

### ISSUE THREAD

**Issue by dmelcer9** [sandboxnu/searchneu-v1#10]
When there is no space before the "4," the results are in the expected order, but when including a space, the results aren't great:

![image](https://user-images.githubusercontent.com/10052511/99540456-80979280-297d-11eb-8ef6-6bb78b383c90.png)

**Comment by gamburgm** [comment]
Thanks for the heads up, we're planning on having a fix out tonight, let us know in the meantime (or otherwise) if you run into any other issues.

**Comment by gamburgm** [comment]
Fix is up now, let us know if you find anything else :)
