### ISSUE TITLE
Infinite scroll with repeating card when searching one class

### ISSUE THREAD

**Issue by anikarabenhorst** [sandboxnu/searchneu-v1#102]
https://searchneu.com/NEU/202210/search/cs4530
- Present on mobile and web
- Searched exact class

https://user-images.githubusercontent.com/49101279/112496598-43904200-8d5b-11eb-96ed-9fb3b07c3422.mp4

**Comment by NEUDitao** [comment]
https://i.imgur.com/bZMAC12.gif another one on desktop for good measure

**Comment by dillonhammer** [comment]
Should be fixed now :)
