### ISSUE TITLE
Feedback button does not work on mobile

### ISSUE THREAD

**Issue by Vocaloiid** [sandboxnu/searchneu-v1#133]
On Chrome's latest version, trying to submit feedback, contact, or do a bug report all have broken submit buttons, clicking submit does nothing.

**Comment by suiboli314** [comment]
iPadOS: 15.1 (19B74) Safari
MacOS: Safari Version 15.1 (17612.2.9.1.20), Firefox 94.0.1 (64-bit), Chrome 96.0.4664.45 (Official Build) (x86_64)
In Feedback/report a bug/Contact window, the submit button doesn’t work for me on none of above browser.
