### ISSUE TITLE
"Professor" profile info no longer returned

### ISSUE THREAD

**Issue by jasonhemann** [sandboxnu/searchneu-v1#146]
Hi,

It used to be that, by searching e.g. "Hemann" on `searchneu.com`, there'd be not only the courses by a given professor for the whatever term is current, but also a kind of profile for that person, with I think an email, office phone number, and office location. However, when I now run that same query, only the course information shows up. I don't recall if the professors' names were ever hyperlinked to that quasi-profile, but they are currently not. 

Was this an intentional change?

**Comment by hankewyczz** [comment]
![image](https://user-images.githubusercontent.com/27775244/162343984-69e87a1e-c895-45d5-894e-fdaf6e54f9df.png)

Appreciate the patience, this issue uncovered a rabbit-hole of related issues which took a while to wrap up. The info returned is from the Northeastern faculty catalog
