### ISSUE TITLE
Semester data cannot load, "Report a bug" does not get sent

### ISSUE THREAD

**Issue by Bryan-Tam** [sandboxnu/searchneu-v1#147]
As the title implies, it seems that multiple components of the site do not work. It seems to be an issue with the API sending and retrieving data but cannot confirm.

**Comment by hankewyczz** [comment]
Looking into the API issue, feedback issue is being tracked (#133).

**Comment by hankewyczz** [comment]
Pushed a fix for the API requests issue, feel free to re-open if it crops up again.
