### ISSUE TITLE
[bug] loads forever on the home page

### ISSUE THREAD

**Issue by jamescd18** [sandboxnu/searchneu-v1#156]
SearchNEU stopped working for me a month ago or something when I first wanted to look at 2022 summer 2 courses, and I shrugged it off at the time, but it looks like it still hasn't been fixed so I figured I should say something. I'm using Safari Version 14.0.1. Screenshots from console and network tab indicate Prisma is throwing an error for some reason.

console
<img width="1334" alt="Screen Shot 2022-03-07 at 2 37 28 AM" src="https://user-images.githubusercontent.com/51571627/156987919-69a86aa2-1622-4065-ae38-fe65440e3f0d.png">

network tab
<img width="1481" alt="Screen Shot 2022-03-07 at 2 41 24 AM" src="https://user-images.githubusercontent.com/51571627/156988468-81488bbc-9ba7-4ca2-be99-f70e600b635a.png">

**Comment by hankewyczz** [comment]
Unfortunately, this is a known issue. We've been talking with the Prisma engineering team - they are aware of the issue & have a replication, but no fix as of yet. We're still trying out various workaround, but this may pop up from time to time. Hopefully, downtime will become unnoticeable as we tinker with short-term solutions

**Comment by jamescd18** [comment]
Ah, understandable!

**Comment by hankewyczz** [comment]
Closing - since implementing the fix (2022-03-10), we haven't had any downtime. Still waiting on an actual solution, but the Prisma-recommended short-term fix seems to be working
