### ISSUE TITLE
Campus says Boston for Silicon Valley, Seattle, and Online class

### ISSUE THREAD

**Issue by dmelcer9** [sandboxnu/searchneu-v1#17]
All of these say "Boston"

![image](https://user-images.githubusercontent.com/10052511/100310054-57c55d80-2f7a-11eb-849b-62d70a878571.png)

But the Terry Ave section is in Seattle:

![image](https://user-images.githubusercontent.com/10052511/100310079-6dd31e00-2f7a-11eb-822a-2580c06a7dde.png)

**Comment by gamburgm** [comment]
Should be fixed now! Let me know if you find anything else though.
