### ISSUE TITLE
Online classes can have meeting times

### ISSUE THREAD

**Issue by dmelcer9** [sandboxnu/searchneu-v1#18]
Predrag Radivojac's class just says "Online Class" as the meeting time:

![image](https://user-images.githubusercontent.com/10052511/100310054-57c55d80-2f7a-11eb-849b-62d70a878571.png)

But the class is being run synchronously online:

![image](https://user-images.githubusercontent.com/10052511/100310396-1bdec800-2f7b-11eb-86c0-8d3b66d4e2ae.png)

**Comment by gamburgm** [comment]
Good point, we don't make any distinction between the two right now, thanks for highlighting this.
