### ISSUE TITLE
"Error - failed to register" when entering number for notifications

### ISSUE THREAD

**Issue by gdavis144** [sandboxnu/searchneu-v1#197]
I suddenly stopped receiving notifications for classes I had signed up for on the site, and when I entered my number to check that they were signed up for I received "error- failed to register". I tried with different numbers, different browsers, and different network connections and had the same outcome. I tried to submit a bug on the site and got "Error- Network Error" and prompted me to create an issue on github.

**Comment by hankewyczz** [comment]
Thanks for the heads up! We just migrated our entire backend infrastructure, and in the process, the notification server wasn't properly set up. 

You should now be able to sign up for new notifications, and all of your old notifications should still be active.
