### ISSUE TITLE
Additional Feature

### ISSUE THREAD

**Issue by kshah1** [sandboxnu/searchneu-v1#209]
> Should include additional options outside of NEU and CPS for [SearchNeu](https://searchneu.com). Here is the included snapshot. <img width="841" alt="Screenshot 2023-04-27 at 3 01 45 PM" src="https://user-images.githubusercontent.com/39974705/234965622-8b5488ae-c33e-4514-a579-1f175aeefb59.png">

@kshah1

**Comment by hankewyczz** [comment]
What would the additional options be? Northeastern only has three colleges — undergraduate+graduate (whose classes are listed together), the Law college, and the College of Professional Studies. Those are the three options above.
