### ISSUE TITLE
"Prerequisite For" field is inaccurate

### ISSUE THREAD

**Issue by ariscript** [sandboxnu/searchneu-v1#229]
I'm looking through courses for Spring 2024 and courses like CS 2500 list no courses that it is a prerequisite for (and there are _many_ considering that it's Fundies 1). 
![image](https://github.com/sandboxnu/searchneu/assets/57048370/ed5a9706-19dc-4283-b2c4-214293909ee8)

Other examples (that I originally found this issue with) were CS 2810 and CS 2800.

Having this feature fixed would be incredibly useful for course planning if we're able to see the future courses that would be unlocked if I were to take this particular course.

**Comment by Lucas-Dunker** [comment]
The bug corresponding to this issue has been fixed and merged into our staging, expect this to be fixed on the actual site in 1-2 weeks!
