### ISSUE TITLE
searchneu.com/NEU/202530 produces a 404

### ISSUE THREAD

**Issue by walker-sean** [sandboxnu/searchneu-v1#280]
Going to the home page after a search for Spring 2025 or pressing Spring 2025 from the selector redirects to [https://searchneu.com/NEU/202530](https://searchneu.com/NEU/202530 )

However, this route seems to not be active.

![image](https://github.com/user-attachments/assets/465316a2-6335-464d-b5bf-a7069fa57301)

**Comment by mehallhm** [comment]
Sorry! Search does not have the Spring 2025 courses in yet, they should be up by Wednesday. We have to manually rescrape Banner for that data and haven't gotten around to it at this time.
