### ISSUE TITLE
Feature Request: Access to Past Terms

### ISSUE THREAD

**Issue by ZibingZhang** [sandboxnu/searchneu-v1#87]
# Feature Request: Access to Past Terms

## Feature Summary
The ability to access data for classes of terms which have already ended.

At the moment, only the current term and terms for which course registration is open are listed under the term dropdown.

## Motivation
For most majors, the higher level courses are not offered every semester.
However, there is typically a set schedule (more or less) for when a particular course is offered.
For instance, the math department claims that geometry is offered in the fall semester of even years.
Since this list is somewhat outdated, I often have had to look through Northeastern's own course catalog of past semesters just to gain insight for when a specific class may be offered.

Many people use SearchNEU as a replacement for Northeastern's own catalog, and so it would make sense to include data regarding past semesters.

**Comment by liustanley** [comment]
Very insightful issue Zibing

**Comment by ZibingZhang** [comment]
Thank you Stanley, the Khoury Office Hours project lead for Sandbox NU!

**Comment by hankewyczz** [comment]
So, we've decided to revert to only keeping the 3 most recent years. Having more than that created a noticeable drag on performance in searching, and more importantly, on the backend. We can't keep all the classes in memory without upgrading our ECS tasks, so we'll be trimming how many years we keep in cache.

**Note: the following paragraph doesn't apply anymore.**
 SearchNEU now has all terms that exist on Banner (ie. going back all the way to 2015). This doesn't seem to slow searches down, but in the future, we might have to delete old terms to keep it snappy and responsive.

----------

All courses are now available at this archive: https://github.com/sandboxnu/course-catalog-api-cache

To understand how to use it, check out this PR updating our documentation (we have nice docs now!!) 
https://github.com/sandboxnu/course-catalog-api/pull/128
