### ISSUE TITLE
Inaccurate prerequisites listed for some classes

### ISSUE THREAD

**Issue by ethan-leba** [sandboxnu/searchneu-v1#9]
**The prerequisites listed on searchNEU for CS4300** https://searchneu.com/202130/cs4300
`Prerequisites: (CS 2510 and EECE 2560 and CS 3500) and (MATH 1260 and MATH 2331 and MATH 2341)`

**The prerequisites found on the myNortheastern registration page for CS4300**
And/Or |   | Test | Score | Subject | Course Number | Level | Grade |  
-- | -- | -- | -- | -- | -- | -- | -- | --
  | ( |   |   | Computer Science | 1500 | Undergraduate | D- |  
Or |   |   |   | Computer Science | 2510 | Undergraduate | D- |  
Or |   |   |   | Computer Science | 3500 | Undergraduate | D- |  
Or |   |   |   | Electrical and Comp Engineerng | 2560 | Undergraduate | D- | )
And | ( |   |   | Mathematics | 1260 | Undergraduate | D- |  
Or |   |   |   | Mathematics | 2331 | Undergraduate | D- |  
Or |   |   |   | Mathematics | 2341 | Undergraduate | D- | )

The same issue appears for MATH4569, seems to present in prerequisites containing parentheses

**Comment by dmelcer9** [comment]
Same for DS4400

**Comment by gamburgm** [comment]
Hey, thanks for letting us know! The team is hoping to tackle this over the next week or two at the latest.

**Comment by megandouli** [comment]
Should be fixed and up on prod soon!

**Comment by ethan-leba** [comment]
Awesome :+1:
