### ISSUE TITLE
Incorrect Course Description - ARTF 2221: Movement and Time Tools

### ISSUE THREAD

**Issue by mmaduri** [sandboxnu/searchneu-v1#99]
The description for **ARTF 2221: Movement and Time Tools** is incorrect. (I teach this) Movement and Time Tools is only 2D animation and does not touch upon 3D modeling and rigging, that is Animation Tools. 

I recommend this description... 
**Introduces skills and software used in animating 2D images and graphics. Explores the basics of key framing, layering, parenting, effects, and workflows in this technology workshop.**

**Comment by NEUDitao** [comment]
Hi!

All of our information is scraped directly from Northeastern's banner/registrar system. I'd recommend asking Northeastern to update the course description if you feel like it doesn't reflect what's taught in the course.

**Comment by mmaduri** [comment]
ah, i see thanks!
